import React from "react";
import Head from "next/head";

const Seo = () => {
	return (
		<Head>
			<title>Book Manager</title>
			{/* <meta name="description" content="Generated by create next app" /> */}
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
};

export default Seo;
